#en:
#  languageCode: en
#  languageName: English
# Uncomment for multilingual sites, and move the default content into corresponding sub-folder.
# contentDir: content/en

th:
  languageCode: th
  languageName: ภาษาไทย
