main:
  - name: About
    url: "#about"
    weight: 3
  - name: Posts
    url: /posts/
    weight: 1
  - name: Docs
    url: /docs/
    weight: 2
  - name: Archive
    url: https://static.mrchoke.org
    weight: 4
